BEGIN_SECTION(CORRECTIVE_BIGRAMS)
SUBS(bi_th, "th", HM_T, HM_H)
SUBS(bi_he, "he", HM_H, THMB_L2)
SUBS(bi_in, "in", HM_I, HM_N)
SUBS(bi_er, "er", THMB_L2, KC_R)
SUBS(bi_an, "an", HM_A, HM_N)
SUBS(bi_on, "on", HM_O, HM_N)
SUBS(bi_at, "at", HM_A, HM_T)
SUBS(bi_en, "en", THMB_L2, HM_N)
SUBS(bi_nd, "nd", HM_N, KC_D)
SUBS(bi_ti, "ti", HM_T, HM_I)
SUBS(bi_es, "es", THMB_L2, HM_S)
SUBS(bi_or, "or", HM_O, KC_R)
SUBS(bi_te, "te", HM_T, THMB_L2)
SUBS(bi_of, "of", HM_O, KC_F)
SUBS(bi_ed, "ed", THMB_L2, KC_D)
SUBS(bi_is, "is", HM_I, HM_S)
SUBS(bi_al, "al", HM_A, KC_L)
SUBS(bi_ar, "ar", HM_A, KC_R)
SUBS(bi_st, "st", HM_S, HM_T)
SUBS(bi_to, "to", HM_T, HM_O)
SUBS(bi_nt, "nt", HM_N, HM_T)
SUBS(bi_ng, "ng", HM_N, KC_G)
SUBS(bi_ha, "ha", HM_H, HM_A)
SUBS(bi_as, "as", HM_A, HM_S)
SUBS(bi_ou, "ou", HM_O, KC_U)
SUBS(bi_io, "io", HM_I, HM_O)
SUBS(bi_le, "le", KC_L, THMB_L2)
SUBS(bi_ve, "ve", KC_V, THMB_L2)
SUBS(bi_co, "co", KC_C, HM_O)
SUBS(bi_me, "me", KC_M, THMB_L2)
SUBS(bi_hi, "hi", HM_H, HM_I)
SUBS(bi_ea, "ea", THMB_L2, HM_A)
SUBS(bi_ch, "ch", KC_C, HM_H)
SUBS(bi_do, "do", KC_D, HM_O)
SUBS(bi_us, "us", KC_U, HM_S)
SUBS(bi_we, "we", KC_W, THMB_L2)
SUBS(bi_up, "up", KC_U, KC_P)
SUBS(bi_if, "if", HM_I, KC_F)
END_SECTION(CORRECTIVE_BIGRAMS)

BEGIN_SECTION(TRIGRAMS)
SUBS(bi_the, "the", HM_T, HM_H, THMB_L2)
SUBS(bi_and, "and", HM_A, HM_N, KC_D)
SUBS(bi_ing, "ing", HM_I, HM_N, KC_G)
SUBS(bi_ion, "ion", HM_I, HM_O, HM_N)
SUBS(bi_tio, "tio", HM_T, HM_I, HM_O)
SUBS(bi_ent, "ent", THMB_L2, HM_N, HM_T)
SUBS(bi_ati, "ati", HM_A, HM_T, HM_I)
SUBS(bi_for, "for", KC_F, HM_O, KC_R)
SUBS(bi_her, "her", HM_H, THMB_L2, KC_R)
SUBS(bi_ter, "ter", HM_T, THMB_L2, KC_R)
SUBS(bi_hat, "hat", HM_H, HM_A, HM_T)
SUBS(bi_tha, "tha", HM_T, HM_H, HM_A)
SUBS(bi_ere, "ere", THMB_L2, KC_R, THMB_L2)
SUBS(bi_ate, "ate", HM_A, HM_T, THMB_L2)
SUBS(bi_his, "his", HM_H, HM_I, HM_S)
SUBS(bi_con, "con", KC_C, HM_O, HM_N)
SUBS(bi_res, "res", KC_R, THMB_L2, HM_S)
SUBS(bi_ver, "ver", KC_V, THMB_L2, KC_R)
SUBS(bi_ons, "ons", HM_O, HM_N, HM_S)
SUBS(bi_nce, "nce", HM_N, KC_C, THMB_L2)
SUBS(bi_men, "men", KC_M, THMB_L2, HM_N)
SUBS(bi_ith, "ith", HM_I, HM_T, HM_H)
SUBS(bi_ted, "ted", HM_T, THMB_L2, KC_D)
SUBS(bi_ers, "ers", THMB_L2, KC_R, HM_S)
SUBS(bi_pro, "pro", KC_P, KC_R, HM_O)
SUBS(bi_thi, "thi", HM_T, HM_H, HM_I)
SUBS(bi_wit, "wit", KC_W, HM_I, HM_T)
SUBS(bi_are, "are", HM_A, KC_R, THMB_L2)
SUBS(bi_not, "not", HM_N, HM_O, HM_T)
SUBS(bi_ive, "ive", HM_I, KC_V, THMB_L2)
SUBS(bi_was, "was", KC_W, HM_A, HM_S)
SUBS(bi_ect, "ect", THMB_L2, KC_C, HM_T)
SUBS(bi_com, "com", KC_C, HM_O, KC_M)
SUBS(bi_per, "per", KC_P, THMB_L2, KC_R)
SUBS(bi_int, "int", HM_I, HM_N, HM_T)
SUBS(bi_one, "one", HM_O, HM_N, THMB_L2)
SUBS(bi_you, "you", HM_Y, HM_O, KC_U)
END_SECTION(TRIGRAMS)

BEGIN_SECTION(WORDS)
SUBS(txt_920a79, "my", HM_T, HM_Y)
SUBS(txt_f31a7f, "his", HM_H, HM_I)
SUBS(txt_da994d, "use", KC_U, THMB_L2)
SUBS(txt_b12f3c, "the", HM_T, HM_H)
SUBS(txt_4607a4, "for", KC_F, KC_R)
SUBS(txt_a4eacd, "and", HM_N, KC_D)
SUBS(txt_6a5f20, "new", HM_N, KC_U)
SUBS(txt_bb0054, "but", KC_B, KC_U)
SUBS(txt_7a4167, "are", HM_A, KC_R)
SUBS(txt_765d98, "you", HM_Y, KC_U)
SUBS(txt_ed01f2, "one", KC_W, KC_U)
SUBS(txt_b236f7, "see", HM_S, THMB_L2)
SUBS(txt_3eb659, "our", HM_O, KC_U)
SUBS(txt_2f09ac, "how", HM_H, KC_U)
SUBS(txt_706e0f, "who", KC_W, HM_O)
SUBS(txt_9dba28, "get", KC_G, HM_T)
SUBS(txt_3b151a, "top", HM_T, KC_P)
SUBS(txt_17c481, "any", HM_N, THMB_L2)
SUBS(txt_227971, "can", KC_C, HM_N)
SUBS(txt_4f3107, "web", KC_W, KC_B)
SUBS(txt_7f2fb4, "all", HM_A, KC_L)
SUBS(txt_8184ea, "was", KC_W, HM_S)
SUBS(txt_8da46f, "has", HM_H, HM_S)
SUBS(txt_cc4577, "had", HM_H, KC_D)
SUBS(txt_b7a9ce, "out", HM_O, KC_G)
SUBS(txt_9dc2dd, "its", HM_I, HM_Z)
SUBS(txt_d9716c, "not", HM_N, HM_T)
SUBS(txt_118fe3, "now", HM_N, HM_Q)
SUBS(txt_912fc8, "may", KC_M, HM_A)
SUBS(txt_769008, "been", KC_B, HM_N)
SUBS(txt_43dc12, "site", HM_S, HM_Y)
SUBS(txt_c6e300, "like", KC_L, HM_K)
SUBS(txt_bdfe53, "with", KC_W, HM_T)
SUBS(txt_c34043, "when", KC_W, HM_N)
SUBS(txt_b7ed41, "find", KC_F, HM_N)
SUBS(txt_f5a0f7, "that", HM_T, HM_H, HM_A)
SUBS(txt_3be4f0, "help", HM_H, KC_L)
SUBS(txt_32aaa6, "were", KC_W, KC_R)
SUBS(txt_4cd926, "also", KC_L, HM_S)
SUBS(txt_be6e87, "back", KC_B, HM_K)
SUBS(txt_5a3966, "view", KC_V, KC_U)
SUBS(txt_89b7d9, "what", KC_W, HM_A)
SUBS(txt_4ffc97, "only", KC_L, HM_Y)
SUBS(txt_7cbf60, "this", HM_T, HM_S)
SUBS(txt_ab1e13, "more", KC_M, KC_R)
SUBS(txt_459770, "some", HM_S, KC_M)
SUBS(txt_37c475, "will", KC_W, KC_L)
SUBS(txt_88cabc, "home", HM_H, KC_M)
SUBS(txt_38b9b4, "free", KC_F, HM_H)
SUBS(txt_7f9ad1, "they", HM_T, HM_Y)
SUBS(txt_79d1b3, "time", HM_T, KC_M)
SUBS(txt_6081a2, "date", KC_D, HM_T)
SUBS(txt_bb894b, "page", KC_P, KC_G)
SUBS(txt_455ae0, "have", HM_H, KC_V)
SUBS(txt_cf60c6, "than", HM_H, HM_N)
SUBS(txt_3e8a23, "here", HM_H, KC_R)
SUBS(txt_9b7855, "your", KC_U, KC_R)
SUBS(txt_7e6bc5, "from", KC_F, THMB_L2)

END_SECTION(WORDS)
