#define BEGIN_WORDS combo_word_that

SUBS(word_that, "that", HM_T, HM_H, HM_A)
SUBS(word_was, "was", KC_W, HM_A)
SUBS(word_with, "with", KC_W, HM_T)
SUBS(word_this, "this", HM_T, HM_H, HM_S)
SUBS(word_from, "from", KC_F, KC_O)
SUBS(word_have, "have", HM_H, HM_A, THMB_L2)
SUBS(word_had, "had", KC_D, HM_H)
SUBS(word_were, "were", KC_W, THMB_L2)
SUBS(word_there, "there", HM_T, THMB_L2, KC_R)
SUBS(word_you, "you", HM_Y, HM_O)
SUBS(word_all, "all", HM_A, KC_L)
SUBS(word_can, "can", KC_C, HM_N)
SUBS(word_her, "her", HM_H, KC_R)
SUBS(word_has, "has", HM_H, HM_S)
SUBS(word_their, "their", HM_T, HM_I, KC_R)

// SUBS(word_been, "been", KC_B, HM_N)
// SUBS(word_more, "more", KC_M, KC_R)
// SUBS(word_when, "when", KC_W, HM_N)
// SUBS(word_will, "will", KC_W, KC_L)
// SUBS(word_would, "would", KC_W, KC_U)
// SUBS(word_other, "other", HM_O, KC_R)
// SUBS(word_its, "its", HM_I, KC_T, HM_S)
// SUBS(word_may, "may", KC_M, HM_Y)
// SUBS(word_these, "these", HM_T, HM_S, THMB_L2)
// SUBS(word_what, "what", KC_W, HM_T)
// SUBS(word_them, "them", HM_T, KC_M)
// SUBS(word_than, "than", HM_T, HM_N)
// SUBS(word_some, "some", HM_S, KC_M, THMB_L2)
// SUBS(word_him, "him", HM_H, KC_M)
// SUBS(word_time, "time", HM_T, HM_I, THMB_L2)
// SUBS(word_such, "such", HM_S, KC_U)
// SUBS(word_new, "new", HM_N, KC_W)
// SUBS(word_about, "about", HM_A, HM_T)
// SUBS(word_out, "out", HM_O, KC_U)
// SUBS(word_also, "also", HM_A, KC_L)
// SUBS(word_any, "any", HM_A, HM_Y)
// SUBS(word_could, "could", KC_C, KC_U, HM_O)
// SUBS(word_our, "our", HM_O, KC_U)
// SUBS(word_then, "then", HM_T, HM_H, HM_N)
// SUBS(word_most, "most", KC_M, HM_O, HM_S)
// SUBS(word_should, "should", HM_S, HM_O, KC_U)
// SUBS(word_said, "said", HM_S, KC_D)
// SUBS(word_your, "your", HM_Y, KC_R)
// SUBS(word_very, "very", KC_V, HM_Y)
// SUBS(word_between, "between", KC_B, THMB_L2)
// SUBS(word_made, "made", KC_M, KC_D)
// SUBS(word_many, "many", KC_M, HM_N)
// SUBS(word_here, "here", HM_H, THMB_L2, KC_R)
//
// SUBS(word_over,"over", HM_O, KC_R)
// SUBS(word_like,"like", KC_L, THMB_L2)
// SUBS(word_those,"those", HM_T, THMB_L2)
// SUBS(word_did,"did", KC_D, KC_D)
// SUBS(word_now,"now", HM_N, KC_W)
// SUBS(word_even,"even", THMB_L2, HM_N)
// SUBS(word_well,"well", KC_W, KC_L)
// SUBS(word_where,"where", KC_W, THMB_L2)
// SUBS(word_must,"must", KC_M, HM_T)
// SUBS(word_people,"people", KC_P, THMB_L2)
// SUBS(word_through,"through", HM_T, HM_H)
// SUBS(word_how,"how", HM_H, KC_W)
// SUBS(word_same,"same", HM_S, THMB_L2)
// SUBS(word_work,"work", KC_W, HM_K)
// SUBS(word_being,"being", KC_B, KC_G)
// SUBS(word_because,"because", KC_B, THMB_L2)
// SUBS(word_man,"man", KC_M, HM_N)
// SUBS(word_life,"life", KC_L, THMB_L2)
// SUBS(word_before,"before", KC_B, THMB_L2)
// SUBS(word_each,"each", THMB_L2, HM_H)
// SUBS(word_much,"much", KC_M, HM_H)
// SUBS(word_under,"under", KC_U, KC_R)
// SUBS(word_years,"years", HM_Y, HM_S)
// SUBS(word_way,"way", KC_W, HM_Y)
// SUBS(word_great,"great", KC_G, HM_T)
// SUBS(word_state,"state", HM_S, THMB_L2)
// SUBS(word_both,"both", KC_B, HM_H)
// SUBS(word_use,"use", KC_U, THMB_L2)
// SUBS(word_upon,"upon", KC_U, HM_N)
// SUBS(word_own,"own", HM_O, HM_N)
// SUBS(word_used,"used", KC_U, KC_D)
// SUBS(word_however,"however", HM_H, KC_R)
// SUBS(word_part,"part", KC_P, HM_T)
// SUBS(word_good,"good", KC_G, KC_D)
// SUBS(word_world,"world", KC_W, KC_D)
// SUBS(word_make,"make", KC_M, THMB_L2)
// SUBS(word_three,"three", HM_T, THMB_L2)
// SUBS(word_while,"while", KC_W, THMB_L2)
// SUBS(word_long,"long", KC_L, KC_G)
// SUBS(word_day,"day", KC_D, HM_Y)
// SUBS(word_without,"without", KC_W, HM_T)
// SUBS(word_just,"just", KC_J, HM_T)
// SUBS(word_men,"men", KC_M, HM_N)
// SUBS(word_general,"general", KC_G, KC_L)
// SUBS(word_during,"during", KC_D, KC_G)
// SUBS(word_another,"another", HM_A, KC_R)
// SUBS(word_little,"little", KC_L, THMB_L2)
// SUBS(word_found,"found", KC_F, KC_D)

#define END_WORDS combo_word_their
