

BEGIN_SECTION(WORDS)
SUBS(bi_hi, "I", HM_H, HM_I)

SUBS(word_that, "that", HM_T, HM_H, HM_A)
SUBS(word_was, "was", KC_NO)
SUBS(word_with, "with", KC_W, HM_T, HM_H)
SUBS(word_this, "this", HM_T, HM_H, HM_S)
SUBS(word_his, "his", KC_NO)
SUBS(word_from, "from", KC_NO)
SUBS(word_which, "which", KC_NO)
SUBS(word_have, "have", HM_H, HM_A, KC_V)
SUBS(word_had, "had", KC_NO)
SUBS(word_they, "they", KC_NO)
SUBS(word_were, "were", KC_NO)
SUBS(word_their, "their", KC_NO)
SUBS(word_you, "you", KC_NO)
SUBS(word_all, "all", KC_NO)
SUBS(word_can, "can", KC_NO)
SUBS(word_her, "her", KC_NO)
SUBS(word_has, "has", KC_NO)
SUBS(word_there, "there", HM_T, THMB_L2, KC_R)
SUBS(word_been, "been", KC_NO)
SUBS(word_more, "more", KC_NO)
SUBS(word_when, "when", KC_NO)
SUBS(word_will, "will", KC_NO)
SUBS(word_would, "would", KC_NO)
SUBS(word_she, "she", KC_NO)
SUBS(word_other, "other", KC_NO)
SUBS(word_its, "its", KC_NO)
SUBS(word_may, "may", KC_NO)
SUBS(word_these, "these", KC_NO)
SUBS(word_what, "what", KC_NO)
SUBS(word_them, "them", KC_NO)
SUBS(word_than, "than", KC_NO)
SUBS(word_some, "some", KC_NO)
SUBS(word_him, "him", KC_NO)
SUBS(word_time, "time", KC_NO)
SUBS(word_into, "into", KC_NO)
SUBS(word_only, "only", KC_NO)
SUBS(word_such, "such", KC_NO)
SUBS(word_new, "new", KC_NO)
SUBS(word_about, "about", KC_NO)
SUBS(word_out, "out", KC_NO)
SUBS(word_also, "also", KC_NO)
SUBS(word_two, "two", KC_NO)
SUBS(word_any, "any", KC_NO)
SUBS(word_first, "first", KC_NO)
SUBS(word_could, "could", KC_NO)
SUBS(word_our, "our", KC_NO)
SUBS(word_then, "then", KC_NO)
SUBS(word_most, "most", KC_NO)
SUBS(word_see, "see", KC_NO)
SUBS(word_should, "should", KC_NO)
SUBS(word_after, "after", KC_NO)
SUBS(word_said, "said", KC_NO)
SUBS(word_your, "your", KC_NO)
SUBS(word_very, "very", KC_NO)
SUBS(word_between, "between", KC_NO)
SUBS(word_made, "made", KC_NO)
SUBS(word_many, "many", KC_NO)
SUBS(word_over, "over", KC_NO)
SUBS(word_like, "like", KC_NO)
SUBS(word_those, "those", KC_NO)
SUBS(word_did, "did", KC_NO)
SUBS(word_now, "now", KC_NO)
SUBS(word_even, "even", KC_NO)
SUBS(word_well, "well", KC_NO)
SUBS(word_where, "where", KC_NO)
SUBS(word_must, "must", KC_NO)
SUBS(word_people, "people", KC_NO)
SUBS(word_through, "through", KC_NO)
SUBS(word_how, "how", KC_NO)
SUBS(word_same, "same", KC_NO)
SUBS(word_work, "work", KC_NO)
SUBS(word_being, "being", KC_NO)
SUBS(word_because, "because", KC_NO)
SUBS(word_man, "man", KC_NO)
SUBS(word_life, "life", KC_NO)
SUBS(word_before, "before", KC_NO)
SUBS(word_each, "each", KC_NO)
SUBS(word_much, "much", KC_NO)
SUBS(word_under, "under", KC_NO)
SUBS(word_s, "s", KC_NO)
SUBS(word_years, "years", KC_NO)
SUBS(word_way, "way", KC_NO)
SUBS(word_great, "great", KC_NO)
SUBS(word_state, "state", KC_NO)
SUBS(word_both, "both", KC_NO)
SUBS(word_use, "use", KC_NO)
SUBS(word_upon, "upon", KC_NO)
SUBS(word_own, "own", KC_NO)
SUBS(word_used, "used", KC_NO)
SUBS(word_however, "however", KC_NO)
SUBS(word_us, "us", KC_NO)
SUBS(word_part, "part", KC_NO)
SUBS(word_good, "good", KC_NO)
SUBS(word_world, "world", KC_NO)
SUBS(word_make, "make", KC_NO)
SUBS(word_three, "three", KC_NO)
SUBS(word_while, "while", KC_NO)
SUBS(word_long, "long", KC_NO)
SUBS(word_day, "day", KC_NO)
SUBS(word_without, "without", KC_NO)
SUBS(word_just, "just", KC_NO)
SUBS(word_men, "men", KC_NO)
SUBS(word_general, "general", KC_NO)
SUBS(word_during, "during", KC_NO)
SUBS(word_another, "another", KC_NO)
SUBS(word_little, "little", KC_NO)
SUBS(word_found, "found", KC_NO)
SUBS(word_here, "here", HM_H, THMB_L2, KC_R)

END_SECTION(WORDS)
