#define BEGIN_WORDS combo_word_that

SUBS(word_that, "that", U_T, U_H, U_A)
SUBS(word_inf, "infinity", U_I, U_N, KC_F)
SUBS(word_the, "The", U_T, U_H, T_L2, U_N)

// SUBS(word_was, "was", KC_W, U_A)
// SUBS(word_with, "with", KC_W, U_T)
// SUBS(word_this, "this", U_T, U_H, U_S)
// SUBS(word_from, "from", KC_F, KC_O)
// SUBS(word_have, "have", U_H, U_A, T_L2)
// SUBS(word_had, "had", KC_D, U_H)
// SUBS(word_were, "were", KC_W, T_L2)
// SUBS(word_there, "there", U_T, T_L2, KC_R)
// SUBS(word_you, "you", U_Y, U_O)
// SUBS(word_all, "all", U_A, KC_L)
// SUBS(word_can, "can", KC_C, U_N)
// SUBS(word_her, "her", U_H, KC_R)
// SUBS(word_has, "has", U_H, U_S)
// SUBS(word_their, "their", U_T, U_I, KC_R)

// SUBS(word_been, "been", KC_B, U_N)
// SUBS(word_more, "more", KC_M, KC_R)
// SUBS(word_when, "when", KC_W, U_N)
// SUBS(word_will, "will", KC_W, KC_L)
// SUBS(word_would, "would", KC_W, KC_U)
// SUBS(word_other, "other", U_O, KC_R)
// SUBS(word_its, "its", U_I, KC_T, U_S)
// SUBS(word_may, "may", KC_M, U_Y)
// SUBS(word_these, "these", U_T, U_S, T_L2)
// SUBS(word_what, "what", KC_W, U_T)
// SUBS(word_them, "them", U_T, KC_M)
// SUBS(word_than, "than", U_T, U_N)
// SUBS(word_some, "some", U_S, KC_M, T_L2)
// SUBS(word_him, "him", U_H, KC_M)
// SUBS(word_time, "time", U_T, U_I, T_L2)
// SUBS(word_such, "such", U_S, KC_U)
// SUBS(word_new, "new", U_N, KC_W)
// SUBS(word_about, "about", U_A, U_T)
// SUBS(word_out, "out", U_O, KC_U)
// SUBS(word_also, "also", U_A, KC_L)
// SUBS(word_any, "any", U_A, U_Y)
// SUBS(word_could, "could", KC_C, KC_U, U_O)
// SUBS(word_our, "our", U_O, KC_U)
// SUBS(word_then, "then", U_T, U_H, U_N)
// SUBS(word_most, "most", KC_M, U_O, U_S)
// SUBS(word_should, "should", U_S, U_O, KC_U)
// SUBS(word_said, "said", U_S, KC_D)
// SUBS(word_your, "your", U_Y, KC_R)
// SUBS(word_very, "very", KC_V, U_Y)
// SUBS(word_between, "between", KC_B, T_L2)
// SUBS(word_made, "made", KC_M, KC_D)
// SUBS(word_many, "many", KC_M, U_N)
// SUBS(word_here, "here", U_H, T_L2, KC_R)
//
// SUBS(word_over,"over", U_O, KC_R)
// SUBS(word_like,"like", KC_L, T_L2)
// SUBS(word_those,"those", U_T, T_L2)
// SUBS(word_did,"did", KC_D, KC_D)
// SUBS(word_now,"now", U_N, KC_W)
// SUBS(word_even,"even", T_L2, U_N)
// SUBS(word_well,"well", KC_W, KC_L)
// SUBS(word_where,"where", KC_W, T_L2)
// SUBS(word_must,"must", KC_M, U_T)
// SUBS(word_people,"people", KC_P, T_L2)
// SUBS(word_through,"through", U_T, U_H)
// SUBS(word_how,"how", U_H, KC_W)
// SUBS(word_same,"same", U_S, T_L2)
// SUBS(word_work,"work", KC_W, U_K)
// SUBS(word_being,"being", KC_B, KC_G)
// SUBS(word_because,"because", KC_B, T_L2)
// SUBS(word_man,"man", KC_M, U_N)
// SUBS(word_life,"life", KC_L, T_L2)
// SUBS(word_before,"before", KC_B, T_L2)
// SUBS(word_each,"each", T_L2, U_H)
// SUBS(word_much,"much", KC_M, U_H)
// SUBS(word_under,"under", KC_U, KC_R)
// SUBS(word_years,"years", U_Y, U_S)
// SUBS(word_way,"way", KC_W, U_Y)
// SUBS(word_great,"great", KC_G, U_T)
// SUBS(word_state,"state", U_S, T_L2)
// SUBS(word_both,"both", KC_B, U_H)
// SUBS(word_use,"use", KC_U, T_L2)
// SUBS(word_upon,"upon", KC_U, U_N)
// SUBS(word_own,"own", U_O, U_N)
// SUBS(word_used,"used", KC_U, KC_D)
// SUBS(word_however,"however", U_H, KC_R)
// SUBS(word_part,"part", KC_P, U_T)
// SUBS(word_good,"good", KC_G, KC_D)
// SUBS(word_world,"world", KC_W, KC_D)
// SUBS(word_make,"make", KC_M, T_L2)
// SUBS(word_three,"three", U_T, T_L2)
// SUBS(word_while,"while", KC_W, T_L2)
// SUBS(word_long,"long", KC_L, KC_G)
// SUBS(word_day,"day", KC_D, U_Y)
// SUBS(word_without,"without", KC_W, U_T)
// SUBS(word_just,"just", KC_J, U_T)
// SUBS(word_men,"men", KC_M, U_N)
// SUBS(word_general,"general", KC_G, KC_L)
// SUBS(word_during,"during", KC_D, KC_G)
// SUBS(word_another,"another", U_A, KC_R)
// SUBS(word_little,"little", KC_L, T_L2)
// SUBS(word_found,"found", KC_F, KC_D)

#define END_WORDS combo_word_inf
